---
- name: Provision and Configure DigitalOcean Droplet
  hosts: localhost
  gather_facts: no
  vars_files:
    - secrets.yml

  roles:
    - provision_droplet

- name: Setup Development Environment on Remote Droplet
  hosts: remote_droplet
  become: yes
  gather_facts: yes
  roles:
    - setup_droplet
    - install_gitlab

