---
- name: Create DigitalOcean Droplet for GitLab
  community.digitalocean.digital_ocean_droplet:
    state: present
    oauth_token: "{{ do_token }}"
    name: "gitlab-tea-project"
    region: "{{ region }}"
    size: "{{ size }}"
    image: "{{ image }}"
    ssh_keys: ["{{ ssh_key_fingerprint }}"]
    backups: false
    ipv6: false
    monitoring: true
  register: gitlab_droplet_info

- name: Extract GitLab droplet public IP address
  set_fact:
    gitlab_droplet_ip: "{{ gitlab_droplet_info.data.droplet.networks.v4 | selectattr('type', 'equalto', 'public') | map(attribute='ip_address') | first }}"

- name: Add GitLab droplet to inventory
  add_host:
    name: "gitlab_droplet"
    ansible_host: "{{ gitlab_droplet_ip }}"
    ansible_user: root
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"

