---
- name: Create DigitalOcean Droplet for Web Server
  community.digitalocean.digital_ocean_droplet:
    state: present
    oauth_token: "{{ do_token }}"
    name: "webserver-tea-project"
    region: "{{ region }}"
    size: "{{ size }}"
    image: "{{ image }}"
    ssh_keys: ["{{ ssh_key_fingerprint }}"]
    backups: false
    ipv6: false
    monitoring: true
  register: webserver_droplet_info

- name: Extract Web Server droplet public IP address
  set_fact:
    webserver_droplet_ip: "{{ webserver_droplet_info.data.droplet.networks.v4 | selectattr('type', 'equalto', 'public') | map(attribute='ip_address') | first }}"

- name: Add Web Server droplet to inventory
  add_host:
    name: "webserver_droplet"
    ansible_host: "{{ webserver_droplet_ip }}"
    ansible_user: root
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"

