---
- name: Create DigitalOcean Droplet
  community.digitalocean.digital_ocean_droplet:
    state: present
    oauth_token: "{{ do_token }}"
    name: "{{ droplet_name }}"
    region: "{{ region }}"
    size: "{{ size }}"
    image: "{{ image }}"
    ssh_keys: ["{{ ssh_key_fingerprint }}"]
    backups: false
    ipv6: false
    monitoring: true
  register: droplet_info

- name: Extract droplet public IP address
  set_fact:
    droplet_ip: "{{ droplet_info.data.droplet.networks.v4 | selectattr('type', 'equalto', 'public') | map(attribute='ip_address') | first }}"

- name: Wait for SSH to become available
  ansible.builtin.wait_for:
    host: "{{ droplet_ip }}"
    port: 22
    delay: 10
    timeout: 300
  delegate_to: localhost

- name: Add new droplet to inventory
  add_host:
    name: "remote_droplet"
    ansible_host: "{{ droplet_ip }}"
    ansible_user: root
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"  # Replace with your SSH key path

